// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SoapXmlMessages.www.thomas_bayer.com {
    
}


[System.ServiceModel.ServiceContractAttribute(Namespace="SoapXmlMessages.www.thomas_bayer.com", ConfigurationName="BLZServicePortType")]
public interface BLZServicePortType {
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://thomas-bayer.com/blz/BLZService/getBankResponse")]
    thomasbayer.com.blz.details getBank(string blz);
}

public interface BLZServicePortTypeChannel : BLZServicePortType, System.ServiceModel.IClientChannel {
}

public class BLZServicePortTypeClient : System.ServiceModel.ClientBase<BLZServicePortType>, BLZServicePortType {
    
    public BLZServicePortTypeClient() {
    }
    
    public BLZServicePortTypeClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public BLZServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public BLZServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public BLZServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public thomasbayer.com.blz.details getBank(string blz) {
        return base.Channel.getBank(blz);
    }
}
namespace thomasbayer.com.blz {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="detailsType", Namespace="http://thomas-bayer.com/blz/")]
    public partial class details : System.Runtime.Serialization.IExtensibleDataObject {
        
        private string bezeichnungField;
        
        private string bicField;
        
        private string ortField;
        
        private string plzField;
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string bezeichnung {
            get {
                return this.bezeichnungField;
            }
            set {
                this.bezeichnungField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string bic {
            get {
                return this.bicField;
            }
            set {
                this.bicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string ort {
            get {
                return this.ortField;
            }
            set {
                this.ortField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string plz {
            get {
                return this.plzField;
            }
            set {
                this.plzField = value;
            }
        }
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
    }
}
